version: 2
executorType: docker
containerInfo:
  - image: ruby:2.4
  - image: redis:latest
  - image: postgres:latest
    env:
      - POSTGRES_USER=mammooc
      - POSTGRES_PASSWORD=mammooc
      - POSTGRES_DB=mammooc_test
stages:
  build:
    workDir: ~/mammooc.org
    environment:
      - COVERALLS_PARALLEL: "true"
      - DATABASE_URL: "postgresql://mammooc:mammooc@localhost/mammooc_test"
    steps:
      - type: checkout
      - type: shell
        name: Install System Dependencies
        command: apt-get update && apt-get -y install build-essential libpq-dev nodejs
      - type: shell
        name: Install Project Dependencies
        command: bundle install
      - type: shell
        name: Create DB
        command: bundle exec rails db:schema:load --trace
      - type: shell
        name: Appy migrations DB
        command: bundle exec rails db:migrate
      - type: shell
        name: Run Test
        command: bundle exec rails spec
      - type: shell
        name: Post coverage to Coveralls
        command: "curl -H \"Content-Type: application/json\" --data \"{\\\"payload\\\": {\\\"build_num\\\": $CIRCLE_BUILD_NUM, \\\"status\\\": \\\"done\\\"} }\" -X POST https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN"
      - type: shell
        name: Run Rubocop
        command: bundle exec rails rubocop:show
      - type: artifacts-store
        path: ~/mammooc.org/rubocop.html
        destination: rubocop
