db:
  image: postgres
  ports:
    - "5432"
redis:
  image: redis
web:
  build: .
  environment:
    - RAILS_ENV=production
    - SECRET_KEY_BASE=somesceretkebasehere4jklfnfrnjkrge
  command: bundle exec rails s -e production -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - redis
