version: "2"
services:
    db:
      image: postgres
      volumes_from: 
        - dbvolume
    dbvolume:
      image: busybox
      volumes:
        - /var/lib/postgresql/data
    redis:
      image: redis
    web:
      extends:
        file: docker-compose-template.yml
        service: web
      build: .
      environment:
        - RAILS_ENV=development
        - RACK_ENV=development
        - WITH_S3=false
        - DATABASE_URL=postgres://postgres@db:5432/
        - REDIS_PROVIDER=redis://redis:6379/
      command: sh 'start.sh'
      ports:
        - "3000:3000"
      links:
        - db
        - redis
