db:
  image: postgres
  ports:
    - "5432"
redis:
  image: redis
  ports:
    - "6379"
web:
  image: jprberlin/mammooc
  environment:
    - RAILS_ENV=production
    - RACK_ENV=production
    - PORT=3000
    - PASSENGER_MAX_POOL_SIZE=3
    - SECRET_KEY_BASE=somesceretkebasehere4jklfnfrnjkrge
  command: foreman start
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - redis
