version: "2"
services:
    db:
      image: postgres
      volumes_from: 
        - dbvolume
      ports:
       - "5432:5432"
    dbvolume:
      image: busybox
      volumes:
        - /var/lib/postgresql/data
    redis:
      extends:
        file: docker-compose-template.yml
        service: redis
      ports:
        - "6379:6379"
    web:
      extends:
        file: docker-compose-template.yml
        service: web
      image: mammooc/mammooc.org
      environment:
        - RAILS_ENV=test
        - RACK_ENV=test
        - WITH_S3=false
        - DATABASE_URL=postgres://postgres@db:5432/
        - FORCE_SSL=false
        - PHANTOM_JS=true
      volumes:
        - ./:/mammooc/
      command: 'rspec'
      links:
        - db
        - redis
