development:
  adapter: postgresql
  encoding: utf8
  database: mammooc_development
  host: localhost
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mammooc_test
  host: localhost
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mammooc_production
  host: localhost
  pool: 5
  username:
  password:
