development:
  adapter: postgresql
  encoding: utf8
  database: mammooc_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: mammooc_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mammooc
  pool: 5
  username:
  password:
