# mammooc configuration file

# Create a new variable
# name: value
# computed_value: 'simply embed a Ruby block'

# Use the variable
# Settings.name     # => value

# See https://github.com/railsconfig/rails_config for more details

root_url: <%= (ENV['DOMAIN'].present? ? "https://#{ENV['DOMAIN']}" : 'https://localhost:3000') %>

# Mailers
sender_notification_address: mammooc <notifications@<%= (ENV['DOMAIN'].present? ? "#{ENV['DOMAIN']}" : 'mammooc.org') %>>

# GroupInvitation
token_length: 16
token_expiry_duration: <%= 1.week %>

# Heroku Deployment with New Relic
domain: <%= (ENV['DOMAIN'].present? ? ENV['DOMAIN'] : ENV['USER']) %>
